apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: w5xsa4le6-nodejs 
  janus-idp.io/tekton: w5xsa4le6-nodejs
  backstage.io/kubernetes-id: w5xsa4le6-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: w5xsa4le6-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml